Onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
]
if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from . import views
from django.urls import path, include


app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name='bucket'),
    path('delete_obj/<str:Key>', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:Key>', views.DownloadBucketObject.as_view(), name='download_obj_bucket')
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>', views.HomeView.as_view(), name='category_filter'),
    path('details/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('bucket/', include(bucket_urls)),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('detail/<int:order_id>', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    # path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove')
]

home/models.py
from django.urls import reverse
from django.utils.text import slugify
from django.db import models


class Category(models.Model):
    sub_cat = models.ForeignKey('self', on_delete=models.CASCADE, related_name='subcat', null=True, blank=True)
    is_sub_cat = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("home:category_filter", args=[self.slug])
    

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(self.name, allow_unicode=True)
        return super().save(*args, **kwargs)


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    image = models.ImageField()
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=3)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("home:product_detail", args=[self.slug])
    

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(self.name, allow_unicode=True)
        return super().save(*args, **kwargs)

home/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from .models import Category, Product
from . import tasks
from django.contrib import messages
from utils import IsAdminUserMixin
from orders.forms import CartAddForm


class HomeView(View):
    def get(self, request, category_slug=None):
        categories = Category.objects.filter(is_sub_cat=False)
        products = Product.objects.filter(available=True)
        if category_slug:
            category = Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request, 'home/home.html', {'products': products, 'categories': categories})


class ProductDetailView(View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        form = CartAddForm()
        return render(request, 'home/detail.html', {'product': product, 'form': form})


class BucketHome(IsAdminUserMixin, View):
    template_name = 'home/bucket.html'

    def get(self, request):
        objects = tasks.all_bucket_objects_tasks()
        return render(request, self.template_name, {'objects': objects})


class DeleteBucketObject(IsAdminUserMixin, View):
    def get(self, request, Key):
        tasks.delete_object_task.delay(Key)
        messages.success(request, 'your objects will be delete soon', 'info')
        return redirect('home:bucket')


class DownloadBucketObject(IsAdminUserMixin, View):
    def get(self, request, Key):
        tasks.download_oject_task.delay(Key)
        messages.success(request, 'your download will start soon', 'info')
        return redirect('home:bucket')

home/templates/home/bucket.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Size</th>
            <th scope="col">Download</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for obj in objects %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{ obj.Key }}</td>
                <td>{{obj.Size|filesizeformat}}</td>
                <td> <a href="{% url 'home:download_obj_bucket' obj.Key %}" class="btn btn-info"> download </a> </td>
                <td> <a href="{% url 'home:delete_obj_bucket' obj.Key %}" class="btn btn-danger"> delete </a> </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2> {{ product.name }} </h2><br>
    <small> {{ product.created }} </small><br>
    <p> {{ product.price }} Toman </p> <br>
    <img src="{{ product.image.url }}" style="width:300px">
    <p> {{ product.description }} </p> <br><br>

    <form action="{% url 'orders:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ form }}
       <input type="submit" value="add to cart"> 
    </form>
{% endblock content %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra_headers %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock extra_headers %}

{% block content %}

    {% for category in categories %}

        <!-- Example split danger button -->
    <div class="btn-group">
        <a href="{{ category.get_absolute_url }}" class="btn btn-danger">{{category.name}}</a>
        <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="visually-hidden">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
            {% for sub in category.subcat.all %}
                <li><a class="dropdown-item" href="{{sub.get_absolute_url}}">{{sub.name}}</a></li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
    <br><br>

    {% for product in products %}
        <div class="card" style="width: 18rem; display:inline-block">
            <a href="{{ product.get_absolute_url }}"> <img src="{{ product.image.url }}" class="card-img-top" alt="..."> </a>
            <div class="card-body">
            <a href="{{ product.get_absolute_url }}"> <h5 class="card-title"> {{ product.name }} </h5> </a>
            <p class="card-text"> {{ product.description }} </p>
            </div>
        </div>
    {% endfor %}
{% endblock content %}